### PR TITLE
First attempt to integrate Appsubmitter into our website!

### PR DESCRIPTION
**Pull request by SeverusYixin**

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Hi @SeverusYixin ,

be careful before merging this! You are adding 5000 files. Github is not meant to be used like this. DO NOT upload the `.venv` folder!

Consider specifying the stuff you use in a requirements.txt or environment.yml file and installing via pypi or conda. Do not ship entire python libraries via a git repository. This has the potential to break your entire project.

**Review by haesleinhuepf — CHANGES_REQUESTED** [review]
Also do not continue working on this branch. 

Start a new attempt, in a new branch. I

**Comment by SeverusYixin** [comment]
ahhh, ok I got it, thank you :)

**Comment by SeverusYixin** [comment]
I should add .venv to my .gitignore

**Comment by haesleinhuepf** [comment]
Yes, and when submitting files / committing changes, you should carefully check what you are submitting, e.g. in Github Desktop:
image

[Read more](https://focalplane.biologists.com/2021/09/04/collaborative-bio-image-analysis-script-editing-with-git/).

**Pull request closed without merging**
